travis:
  secure:
    BINSTAR_TOKEN: g2HR5inJYZk04ifc3Y/ZRcE8bOcnfxQXEQtzGkhoeuZ4XWmH7WLUUs2A745BzksE3hZL63/TUzjo/rjFd0SVSyWv9Di5buje04uG76sBwwj1XvLUFpmkc1sFr3WQ6bKrg5yXfdP6h04RDwkNAQQ1WSdW/+iCMdZ0xWVS/toXgFb6T7DmsXqeop2P4ZBG6ACFZWXRmVsBhnw6KX1gMyr3XHf1e5HigOglv0n6ZRlThweSKnIXGj46c/WDk5e0qRTWXRYdvhx0n+UIgrcZbIdQp3E6SPeAUVr3EgLqhzbeuSKqipkJ1HkbQqpbD0Ft3ttwnZBviKzql41UwOhn9NlVwZw9MEFCoHuKpEkHq0QkgWaixFLLlX2HKVyl7YuRzrh1iFFbOJHkKw4N47a5sqsY9srrZw5uacMuL7vJWzUGdgXiI278tq1TUVvNYlN8gv/lC4c3tFhrJDksHR7AnP1Eh9zc8ZgSaNcVN2we8QnGA4bSG//vboimjdLj71IDtQUo+t0ouglwCqYhHGbR+Gp2uPcxljsvn0/xDvWGCdVtVfHIqKnqAD+e+UdFBWO+G37zTn2HRhHg6bSb8m/G/yYtPON9W5W0TyJp0xZSEYj3pCoQC2bb24sOVYdphLSzlUfDJ+LtG68HEciApXsdXNmd9AUwyo7j06ssFYbsZFXiqaw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
